require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EggClutchesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # EggClutch. As you add validations to EggClutch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EggClutchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all egg_clutches as @egg_clutches" do
      egg_clutch = FactoryGirl.create(:egg_clutch)
      get :index, {}, valid_session
      expect(assigns(:egg_clutches)).to eq([egg_clutch])
    end
  end

  describe "GET show" do
    it "assigns the requested egg_clutch as @egg_clutch" do
      egg_clutch = FactoryGirl.create(:egg_clutch)
      get :show, {:id => egg_clutch.to_param}, valid_session
      expect(assigns(:egg_clutch)).to eq(egg_clutch)
    end
  end

  describe "GET new" do
    it "assigns a new egg_clutch as @egg_clutch" do
      get :new, {}, valid_session
      expect(assigns(:egg_clutch)).to be_a_new(EggClutch)
    end
  end

  describe "GET edit" do
    it "assigns the requested egg_clutch as @egg_clutch" do
      egg_clutch = FactoryGirl.create(:egg_clutch)
      get :edit, {:id => egg_clutch.to_param}, valid_session
      expect(assigns(:egg_clutch)).to eq(egg_clutch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EggClutch" do
        expect {
          post :create, {:egg_clutch => valid_attributes}, valid_session
        }.to change(EggClutch, :count).by(1)
      end

      it "assigns a newly created egg_clutch as @egg_clutch" do
        post :create, {:egg_clutch => valid_attributes}, valid_session
        expect(assigns(:egg_clutch)).to be_a(EggClutch)
        expect(assigns(:egg_clutch)).to be_persisted
      end

      it "redirects to the created egg_clutch" do
        post :create, {:egg_clutch => valid_attributes}, valid_session
        expect(response).to redirect_to(EggClutch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved egg_clutch as @egg_clutch" do
        post :create, {:egg_clutch => invalid_attributes}, valid_session
        expect(assigns(:egg_clutch)).to be_a_new(EggClutch)
      end

      it "re-renders the 'new' template" do
        post :create, {:egg_clutch => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested egg_clutch" do
        egg_clutch = EggClutch.create! valid_attributes
        put :update, {:id => egg_clutch.to_param, :egg_clutch => new_attributes}, valid_session
        egg_clutch.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested egg_clutch as @egg_clutch" do
        egg_clutch = EggClutch.create! valid_attributes
        put :update, {:id => egg_clutch.to_param, :egg_clutch => valid_attributes}, valid_session
        expect(assigns(:egg_clutch)).to eq(egg_clutch)
      end

      it "redirects to the egg_clutch" do
        egg_clutch = EggClutch.create! valid_attributes
        put :update, {:id => egg_clutch.to_param, :egg_clutch => valid_attributes}, valid_session
        expect(response).to redirect_to(egg_clutch)
      end
    end

    describe "with invalid params" do
      it "assigns the egg_clutch as @egg_clutch" do
        egg_clutch = EggClutch.create! valid_attributes
        put :update, {:id => egg_clutch.to_param, :egg_clutch => invalid_attributes}, valid_session
        expect(assigns(:egg_clutch)).to eq(egg_clutch)
      end

      it "re-renders the 'edit' template" do
        egg_clutch = EggClutch.create! valid_attributes
        put :update, {:id => egg_clutch.to_param, :egg_clutch => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested egg_clutch" do
      egg_clutch = EggClutch.create! valid_attributes
      expect {
        delete :destroy, {:id => egg_clutch.to_param}, valid_session
      }.to change(EggClutch, :count).by(-1)
    end

    it "redirects to the egg_clutches list" do
      egg_clutch = EggClutch.create! valid_attributes
      delete :destroy, {:id => egg_clutch.to_param}, valid_session
      expect(response).to redirect_to(egg_clutches_url)
    end
  end

end
